### ISSUE TITLE
how to use Distiller?

### ISSUE THREAD

**Issue by Chenhait** [dongtsi/DeepAID#3]
hi, I read the paper 'DeepAID: Interpreting and Improving Deep Learning-based
Anomaly Detection in Security Applications'. It is a wonderful work!
I try to use the Distiller, however, I did not find any code about Distiller.
Thank you so much if any advance!!!

**Comment by sorrowwwww** [comment]
Hello, I have the same problem. Have you solved the problem of the distiller？

**Comment by dongtsi** [comment]
Distiller is preliminary and only supports tabular data now. We are planning to expand our work to the journal version, including the expansion of the applicability of Distiller. At that time, the code of Distiller will be updated in **another** repo.
If you really need help, please email me, I'd be happy to help.
