### ISSUE TITLE
关于“graph_link_embed_apt”中“anomaly_node_pair”的含义

### ISSUE THREAD

**Issue by ljblob** [dongtsi/DeepAID#4]
作者您好，请问在“graph_link_embed_apt”文件中“anomaly_node_pair”具体指什么含义呢？是“anomaly_node_pair”中两个节点都是异常节点吗？

**Comment by dongtsi** [comment]
是的，graph_link_embed_apt中解释的[RAID’20](https://www.usenix.org/conference/raid2020/presentation/bowman)这个GLGV, GLGV判断的是图中的边是否是异常，这里我就用两个node的端点来表示这条边了。具体您可以参考GLGV的论文。

**Comment by dongtsi** [comment]
I'll close this one. Thanks
